### ISSUE TITLE
Exectuting multiple commands in 1 query

### ISSUE THREAD

**Issue by ant1j** [MonetDB/MonetDBLite-Python#36]
It seems so far that it is not possible for monetdblite to handle multiple SQL statements in one `execute` command:

```python
In [17]: cc = conn.cursor()

In [22]: r = cc.execute('''
...: CREATE TABLE test1 ( i int );
...: CREATE TABLE test2 ( i int );
...: CREATE TABLE test3 ( i int );
...: ''')

In [26]: cc.execute(''' SELECT * FROM tables WHERE system=0'''); cc.fetchall()
Out[26]:
[[6465, 'test1', 2000, None, 0, 0, 0, 0, 0]]
```

It would be quite useful, especially when trying to execute a full SQL file with multiple statements.

It try to look at the `executemany()` function, but it does not seems to be adapted for that use-case

**Comment by kutsurak** [comment]
Hi @ant1j,

The way we interpret [PEP-249](https://www.python.org/dev/peps/pep-0249/#id15), is that indeed `execute` accepts one SQL operation (query or command), and I don't believe this will change, because it would create a number of serious implementation issues. For instance, if there is a syntax error in one of your statements how do we report it? How are we to handle any parameters following the SQL text? etc

On the other hand, I have also felt the need to execute simple SQL scripts, so I wrote [this](https://github.com/MonetDBSolutions/mal_analytics/blob/master/mal_analytics/db_manager.py#L135) method. The argument is the filename of the script that you want to execute, and the cursor is an attribute of the class that defines this method. The idea here is that we accumulate lines until we encounter a semicolon, join them to create the text of one operation, execute it, and continue until there are no more lines.

This method can handle comments starting at the beginning of line and multi-line statements like 
```sql
-- This comment gets handled correctly
CREATE TABLE foo (
   col1 int,
   col2 int
);
```
but it is a quick and dirty hack and probably will fail if you try to do something more complicated. Specifically it will fail for:
```sql
CREATE TABLE foo (
   col1 int,  -- This comment creates problems.
   col2 int
);
```
Keep also in mind that it probably is not the most efficient piece of Python ever written.

I hope this helps,
Panos.

**Comment by ant1j** [comment]
OK `execute_sql_script` is a workaround, but ultimately the SQL parsing should not be done by python, for all the problems you mention and beyond (e.g. comments or  `/* ... */` multi-line comments with `;` in it...).

Googling around I realized that python clients for other DB (sqlite, mysql) enforcing PEP-249 follow the "1 statement rule" for `execute`. 
They have dedicated methods or approach `sqlite.executesqcript()` and `many=True` for mysql

I was more used to `psycopg2` which allow multiple statements to be run without complaining.
The issues you mentioned (report syntax error, parameters) are handled by the DB itself.

Monetdb can handle multiple statements through other clients/interfaces (correct me if I am wrong), wouldn't it be possible to expose such feature in `monetdblite`?

Ultimately, I guess that instead of having monetdb within python, I should do it the other way round: having python within monetdb through "Embedded Python".
BTW do you know if a `monetdb-python3` package will be available soon? (sorry to ask maybe it is a totally different project)?

**Comment by kutsurak** [comment]
Hi again,

> Monetdb can handle multiple statements through other clients/interfaces (correct me if I am wrong), wouldn't it be possible to expose such feature in `monetdblite`?

It is possible, but I am not sure how much effort it would require for the implementation. In any case, we are currently working on a project to re-engineer MonetDB in order to produce the both the embedded library and the full database from the same codebase. Right now we are using [MonetDBLite-C](https://github.com/MonetDB/MonetDBLite-C). Until that project is finished, I am hesitant to add new features.

The next planned [release](https://github.com/MonetDB/MonetDBLite-Python/milestone/2) for MonetDBLite-Python will make it fully compliant to PEP-249 (there are still some details that are not implemented, or that are different). 

> BTW do you know if a `monetdb-python3` package will be available soon? (sorry to ask maybe it is a totally different project)?

In fact this will be available in the next feature release of MonetDB. The branch is named April-2019, so I would expect it sometime next month, but we have no exact date yet.

Best regards,
Panos.
