### ISSUE TITLE
Support for Data Vaults

### ISSUE THREAD

**Issue by arnikz** [MonetDB/MonetDBLite-Python#43]
Hi,

I'd like to use [Data Vaults](https://www.monetdb.org/Documentation/Extensions/DataVaults) (in particular SAM/BAM). Any suggestions on how to enable this feature with MonetDBLite? Thank you.

**Comment by kutsurak** [comment]
Hi and sorry for the delay in answering,

At this moment there is no way to use data vaults, with MonetDB Lite. The issue is that currently the C library is a separate code base than MonetDB itself, with most extensions (data vaults included) disabled.

 We are in the process of rewriting MonetDB Lite so that the C library is produced from the same code base as MonetDB itself. I expect a first version to be released sometime in the Spring. I will have to check with my colleague, but I believe it will be possible to use extensions like data vaults with it.

Best regards,
Panos.

**Comment by kutsurak** [comment]
Hi again,

After talking to my colleague, I am afraid that the answer is no, it will not be possible even after the rewrite. 

The problem is the following:  The implementation of data vaults in MonetDB depends on external libraries. In order to read BAM files for example, we link with a library that implements the functionality for reading and writing BAM files. 

MonetDBLite on the other hand needs to be a single C library without external dependencies, because it needs to be embedded into a Python or R process. 

Panos.

**Comment by arnikz** [comment]
Thanks for your swift reply. I'll try the DB server version.
